language: python
python:
  - "3.4"
  - "3.5"
  - "pypy3"
install:
  - pip install -r requirements.txt
  - pip install codecov
script:
  - python bin/sensed -c config/config.sample.json --ci
  - coverage run bin/sensed -c config/config.sample.json --ci
after_success:
  - codecov
  - bash <(curl -s https://codecov.io/bash)