language: python
python:
  - "3.4"
  - "3.5"
  - "pypy3"
install: "pip install -r requirements.txt"
script:
  python sensed.py -c config/config.sample.json --ci
after_success:
  - bash <(curl -s https://codecov.io/bash)