[sensed]

name = 'testnode'
test = true
host = '0.0.0.0'
port = 3000
sensors = [ 'sensed.modules.datetime' ]

# Settings for the datetime sensor module
[sensed-modules-datetime]

# Available formats: unix, 12h, 24h, iso, or all
formats = [ 'all' ]